name: Publish github-cli docker image

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 8 * * 6'
  workflow_dispatch:

env:
  REPOSITORY_NAME: wilsonm/github-cli
  GH_CLI_DOCKER_TAG: ${{ vars.GH_CLI_DOCKER_TAG }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and publish github-cli
      run: |
        docker build --tag ${REPOSITORY_NAME}:${GH_CLI_DOCKER_TAG} -f github-cli-docker/Dockerfile .
        echo "$DOCKER_PASSWORD" | docker login -u="${DOCKER_USERNAME}" --password-stdin
        docker push ${REPOSITORY_NAME}:${GH_CLI_DOCKER_TAG}
        docker logout
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
